// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9CUWy1qzHxnEYGAucLWIfSUFn7w1GSZU',
    appId: '1:193830955528:web:676bee49c978f113837fbd',
    messagingSenderId: '193830955528',
    projectId: 'voyage-dea50',
    authDomain: 'voyage-dea50.firebaseapp.com',
    storageBucket: 'voyage-dea50.appspot.com',
    measurementId: 'G-8J63KS1ZJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6u8Wa6m0vGtz1fQleNhMB_PzmC_rNgMk',
    appId: '1:193830955528:android:f6ec35fd92f351ef837fbd',
    messagingSenderId: '193830955528',
    projectId: 'voyage-dea50',
    storageBucket: 'voyage-dea50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_XX4l0BCwEZYvX-AeF0eGuBbyqW7ISHY',
    appId: '1:193830955528:ios:e7fec0108bc21579837fbd',
    messagingSenderId: '193830955528',
    projectId: 'voyage-dea50',
    storageBucket: 'voyage-dea50.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_XX4l0BCwEZYvX-AeF0eGuBbyqW7ISHY',
    appId: '1:193830955528:ios:5fb9a32ef35429df837fbd',
    messagingSenderId: '193830955528',
    projectId: 'voyage-dea50',
    storageBucket: 'voyage-dea50.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
